### ISSUE TITLE
Download checksum verification fails on FreeBSD 13.1

### ISSUE THREAD

**Issue by edolnx** [kennyp/asdf-golang#90]
**Describe the bug**
When attempting to download the golang archive on FreeBSD 13 the checksum fails to verify with the following error:
```
verifying checksum
sha256sum: option requires an argument -- c
usage: sha256sum [-pqrtx] [-c file] [-s string] [files ...]
Authenticity of package archive can not be assured. Exiting.
```
This can be worked around by temporarily renaming the `sha256sum` tool to `sha256sum.fbsd` and re-running the installer.

**To Reproduce**
1. On a FreeBSD 13.1 amd64 system, attempt to `asdf install golang 1.17.13`
2. See error

**Expected behavior**
This seems to be due to an incompatibility of the between the FreeBSD 13 and Linux versions of the sha256sum tool. Temporarily renaming the `sha256sum` binary and re-running the command worked. Looking at the code, if `sha256sum` is not found the `shasum` tool is used instead. I have also tested on an older FreeBSD install (11.4) which does not include the `sha256sum` tool and everything works as expected.

**Additional context**
Since this is a bug specific to newer versions of FreeBSD, I am unsure how best to resolve this issue which is why I am opening a bug instead of submitting a PR to correct it. It may make more sense to simply use only the `shasum` tool on the FreeBSD platform, or it may make more sense to simply try that tool first in all cases? I'm happy to do the PR for whatever the discussion of this issue feels is appropriate.

**Comment by kennyp** [comment]
I'll have to spin up a FreeBSD box and check it out. I really wish Github Actions supported FreeBSD and we could have caught this earlier. :cry:

**Comment by slewsys** [comment]
@kennyp I think that PR #87 can be safely applied to resolve this issue.  In particular, macOS bash v3.2 also supports process substitution, so no problems there.  The issue is that FreeBSD `sha256sum`  is not the same as GNU `sha256sum`.  In particular, FreeBSD's  option `-c` expects and argument (which process substitution provides in the form of a named pipe).

If you insist on using GNU `sha256sum`, at least provide an environment variable so that the path can be disambiguated.  For instance, on FreeBSD,  installing GNU coreutils adds /usr/local/bin/gsha256sum.  The patch below defines environment variable SHA256SUM_CMD which defaults to /usr/bin/sha256sum, but can be overriden by FreeBSD users with: `export SHA256SUM_CMD=/usr/local/bin/gsha256sum`.

````diff
diff --git a/bin/download b/bin/download
index 7a00a03..e9764f6 100755
--- a/bin/download
+++ b/bin/download
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 set -eu
+: ${SHA256SUM_CMD:=/usr/bin/sha256sum}
+: ${SHASUM_CMD:=/usr/bin/shasum}
+
 [ "${BASH_VERSINFO[0]}" -ge 3 ] && set -o pipefail
 
 PLUGIN_DIR="$(dirname "${BASH_SOURCE[0]}")/.."
@@ -14,11 +17,11 @@ check_shasum() {
 
     authentic_checksum=$(<"$authentic_checksum_file")
 
-    if command -v sha256sum >/dev/null 2>&1; then
-        sha256sum \
+    if command -v $SHA256SUM_CMD >/dev/null 2>&1; then
+        $SHA256SUM_CMD \
             -c <<<"$authentic_checksum  $archive_file_name"
-    elif command -v shasum >/dev/null 2>&1; then
-        shasum \
+    elif command -v $SHASUM_CMD >/dev/null 2>&1; then
+        $SHASUM_CMD \
         -a 256 \
         -c <<<"$authentic_checksum  $archive_file_name"
     else
```
